security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,/static/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,/druid/**,
    /oauth/deleteToken, /backReferer,/extractToken
server:
  port: 18001
spring:
  redis:
    database: 0
    host: ${REDIS_HOST:172.20.100.30}
    port: ${REDIS_PORT:6379}
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:172.20.100.30}:${MYSQL_PORT:3306}/titan-security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: one
      password: df6100
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  freemarker:
      request-context-attribute: request
      #template-loader-path: classpath:/templates
      #check-template-location: true
      #content-type: text/html
      #suffix: .ftl
  rabbitmq:
      host: ${MQ_HOST:172.20.100.29}
      port: 5672
      username: guest
      password: guest

logging:
  file: logs/auth-server.log
  level:
      com.wisdom.auth: debug