server:
  port: 18002
# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:172.20.100.30}:${MYSQL_PORT:3306}/titan-security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: one
      password: df6100
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  redis:
      database: 0
      host: ${REDIS_HOST:172.20.100.30}
      port: ${REDIS_PORT:6379}
  rabbitmq:
      host: ${MQ_HOST:172.20.100.29}
      port: 5672
      username: guest
      password: guest

# 权限配置
security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,
    /user/name/**,/user/phone/**,/role/user/**,/menu/user/*,/client/all
  basic:
    enable: false
  oauth2:
    resource:
      jwt:
        key-uri: http://172.21.29.14:18001/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
# mybatis 配置
mybatis:
  type-aliases-package: com.wisdom.auth.common.db.mapper.model
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  file: logs/auth-server-db.log
  level:
    com.wisdom.auth: debug